title: aero-pi-ogn-receiver Documentation
description: Documentation for aero-pi-ogn-receiver - an installable OGN/FLARM receiver manager for Raspberry Pi

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

url: https://caenfalaiseplaneurs.github.io
baseurl: /aero-pi-ogn-receiver

exclude:
  - Gemfile
  - Gemfile.lock
